In [1]:
import numpy as np
print("done")

done


In [ ]:
#0 D array
a=23
arr=np.array(a)
print(type(a))
print(type(arr))

<class 'int'>
<class 'numpy.ndarray'>


In [8]:
#1 D array
a=[10,20,30,40]
print(a)
print(type(a))
arr=np.array(a)
print(type(arr))
print(arr[1])

[10, 20, 30, 40]
<class 'list'>
<class 'numpy.ndarray'>
20


In [10]:
#2 D array
a=[1,2,3]
b=[4,5,6]
c=[a,b]
arr=np.array([a,b])
print(arr)
print(arr[1,1])

[[1 2 3]
 [4 5 6]]
5


In [19]:
#3D array

a=[1,2,3]
b=[4,5,6]
c=[6,7,8]
d=[3,5,0]
x=[a,b]
y=[c,d]
z=[x,y]
arr=np.array(z)
print(arr)
print(type(arr))
print(arr[1,1,2])
arr.shape

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [3 5 0]]]
<class 'numpy.ndarray'>
0


(2, 2, 3)

In [ ]:
arr1 =np.array([1,2,3])
arr2=np.array([2,3,4])
print(arr1+arr2)


[3 5 7]


In [18]:
arr=np.array[1,2,3,4,5,6,7,8,9,10]
a=arr.reshape(4,3)
print(a)

TypeError: 'builtin_function_or_method' object is not subscriptable