## Numpy


In [1]:
import numpy as np

In [3]:
array = [1,2,3,4]
print(array)

[1, 2, 3, 4]


In [5]:
print(type(array))

<class 'list'>


In [6]:
array=array*2
array

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
for i in array:
    i*=2
    print([i])


[2]
[4]
[6]
[8]
[2]
[4]
[6]
[8]


In [11]:
array=np.array(array)
print(array)

[1 2 3 4 1 2 3 4]


In [12]:
print(type(array))

<class 'numpy.ndarray'>


In [13]:
array = array*2
print(array)

[2 4 6 8 2 4 6 8]


In [14]:
array1=[1,2,3,4,5,6,7,8]
print(array+array1)

[ 3  6  9 12  7 10 13 16]


In [15]:
arr=np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.dtype)

## dtype - int
the "dtype" is a keyword
numpy have diff type of data type like int64 ect..

+ int8,
+ int16,
+ int32,
+ int64

+ int8 (1 byte) ==>  2^8=256 => -128 --> 0 -->128


In [2]:
array=np.array([1,2,3,4,5],dtaype=int8)

NameError: name 'int8' is not defined

In [4]:
array=np.array([1,2,3,4,130],dtype=np.int8)

print(array)
print(array.dtype)
print(array.nbytes) #size

OverflowError: Python integer 130 out of bounds for int8

In [66]:
array=np.array([130,2,3,4,5],dtype=np.int8)

OverflowError: Python integer 130 out of bounds for int8

In [25]:
array=np.array([1,2,3,4,5],dtype=np.int16)
array

array([1, 2, 3, 4, 5], dtype=int16)

### Float

float stored from float16

also have str , Boolean

In [5]:
array=np.array([1.2,2.4,3.3,4.2,5.9],dtype=np.float16)
array
type(array)
print(array.dtype)

float16


In [6]:
array=np.array([1,2],dtype=np.str_)
array

array(['1', '2'], dtype='<U1')

In [7]:
print(array.dtype)

<U1


In [8]:
array=np.array([1,2,3,4,5],dtype=np.bool_)

### Object

In [9]:
array=np.array([1,2,3,4,5,"hii",True],dtype=np.object_)

In [10]:
array.dtype

dtype('O')

## type casting

In [67]:
array = np.array([1,2,3,4])
type(array)

numpy.ndarray

In [68]:
array.dtype

dtype('int64')

In [69]:
array = array.astype(np.str_)
array.dtype

dtype('<U21')

In [70]:
array=array.astype(np.float16)
array.dtype

dtype('float16')

## Multi dimensions & Reshape

+ zero dim(only one value) =>0D
+ one dim(one line) ==>1D array
+ Matrix ==>2D
+ collection of matrix ==> 3D
+ etc...

In [15]:
array = np.array([1,2,3,4,5])
array.dtype

dtype('int64')

In [6]:
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [1, 2, 3]
    ],
    [
        [4, 5, 6],
        [4, 5, 6]
    ]
])

print(arr)
print(arr.shape)
    

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
(2, 2, 3)


In [7]:
print(arr[1][1][2])

6


In [8]:
print(arr[0,1,2])

3


In [4]:
#Reshape

In [2]:
arr=arr.reshape(6,2)
print(arr)

[[1 2]
 [3 1]
 [2 3]
 [4 5]
 [6 4]
 [5 6]]


In [6]:
arr=arr.reshape(-1,4)
arr

array([[1, 2, 3, 1],
       [2, 3, 4, 5],
       [6, 4, 5, 6]])

In [8]:
print(arr[0]) # zero based indexing

[1 2 3 1]


In [9]:
print(arr[1])

[2 3 4 5]


In [10]:
print(arr[-1]) #negative indexing

[6 4 5 6]


In [13]:
print(arr[-1])

[6 4 5 6]


In [14]:
print(arr[0][1])

2


In [16]:
print(arr[1:3])

[[2 3 4 5]
 [6 4 5 6]]


In [17]:
print(arr[1:3:2])

[[2 3 4 5]]


In [19]:
print(arr[:-1]) #ship the last row

[[1 2 3 1]
 [2 3 4 5]]


In [20]:
print(arr[::-1])

[[6 4 5 6]
 [2 3 4 5]
 [1 2 3 1]]


# cloumn

In [23]:
print(arr[:,1]) # :, is used row la irukuradhula ellame neye asumpaniko column ku mattum na kudukura

[2 3 4]


In [13]:
print(arr)

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]


In [12]:
print(arr[::,-1])

[[1 2 3]
 [4 5 6]]


In [11]:
print(arr[1:2:1, 0:1:1])

[[[4 5 6]]]


In [34]:
print(arr[1::1,2::1])

[[4 5]
 [5 6]]


# Arithmetic

In [36]:
arr=np.array([1,11,22,43,55])
arr

array([ 1, 11, 22, 43, 55])

In [37]:
print(arr+1) #scelar values

[ 2 12 23 44 56]


In [38]:
print(arr-5)

[-4  6 17 38 50]


In [39]:
print(arr**2)

[   1  121  484 1849 3025]


In [40]:
brr=np.sqrt(arr)
brr

array([1.        , 3.31662479, 4.69041576, 6.55743852, 7.41619849])

In [41]:
print(np.round(brr))

[1. 3. 5. 7. 7.]


In [42]:
print(np.floor(brr))

[1. 3. 4. 6. 7.]


In [43]:
print(np.ceil(brr))

[1. 4. 5. 7. 8.]


In [44]:
brr =np.array([1,3,4,2,3])
brr

array([1, 3, 4, 2, 3])

In [45]:
arr+brr

array([ 2, 14, 26, 45, 58])

In [46]:
print(brr/arr)

[1.         0.27272727 0.18181818 0.04651163 0.05454545]


In [47]:
print(arr*brr)

[  1  33  88  86 165]


In [48]:
print(np.pi)

3.141592653589793


In [51]:
print(np.all)

<function all at 0x000001F629CF1580>


In [52]:
age=np.array([22,33,11,5,66,34])

In [53]:
print(age>18)

[ True  True False False  True  True]


In [54]:
print(age>=18)

[ True  True False False  True  True]


In [55]:
age[age<18]=17.5
print(age)

[22 33 17 17 66 34]


In [56]:
age[age>50]=50
print(age)

[22 33 17 17 50 34]


# Broadcasting

In [1]:
import numpy as np

In [2]:
arr=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [3]:
arr1 = np.array([1,2,3])

In [4]:
arr.shape

(3, 3)

In [5]:
arr1.shape

(3,)

In [6]:
print(arr*arr1)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [8]:
arr2=np.array([[1],[2],[3]])

In [10]:
print(arr.shape)
print(arr2.shape)
# row same , or 1

print(arr*arr2)

(3, 3)
(3, 1)
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


## Function

In [13]:
arr=np.zeros(11)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
arr=np.zeros((10,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
arr=np.ones((1))

In [18]:
arr

array([1.])

In [20]:
arr=np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [22]:
arr=np.full((2,3),33)
arr

array([[[33, 33, 33],
        [33, 33, 33]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [24]:
#identicaly marix

arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
arr=np.empty(4) # values yedhuyum assign panama grabage value ahh kudukum
print(arr) # like as c pro

[1. 1. 1. 1.]


In [36]:
arr=np.empty((2,3)) # nambaluku oru array vennum but values aprma insert analam irukum podhu idha empty use panikalam
arr# 0's,1's ahh veda fast ahh irukum yen na namba yedha values kudukala adhunala

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29061074e-306, 1.89146896e-307, 7.56571288e-307]])

In [37]:
arr=np.arange(0,100,2) # start,end,step
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [43]:
arr=np.linspace(0,100,6)# start,end,count
print(arr)

[  0.  20.  40.  60.  80. 100.]


## Ageregate

In [51]:
print(np.mean(arr))
print(np.sum(arr))
print(np.median(arr))

50.0
300.0
50.0


In [52]:
print(np.max(arr))
print(np.std(arr))

100.0
34.15650255319866


In [46]:
print(np.var(arr))

1166.6666666666667


In [53]:
print(np.min(arr))
print(np.argmin(arr)) # where index la min num iruku

0.0
0


In [2]:
arr = np.array([
    [1,2,3],[4,5,6]])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sum(arr))

print(np.sum(arr, axis=0)) # column add
print(np.sum(arr, axis=1)) #row add

1
6
0
5
21
[5 7 9]
[ 6 15]


## Fitering

In [1]:
import numpy as np

In [2]:
marks = np.array([50,100,44,45,87])
print(marks)

[ 50 100  44  45  87]


In [4]:
print(marks[marks>=50])

[ 50 100  87]


In [5]:
print(marks>=50)

[ True  True False False  True]


In [6]:
pass_marks=(marks[marks>=50])
print(pass_marks)

[ 50 100  87]


In [7]:
even=(marks[marks% 2==0])
print(even)

[ 50 100  44]


In [9]:
pass_marks=(marks[(marks>=50) & (marks<=70)])
print(pass_marks)

[50]


In [10]:
pass_marks=(marks[(marks>=50) | (marks%2==0)])
print(pass_marks)

[ 50 100  44  87]


In [11]:
## multidiemisional array

arr = np.array([
    [1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
even =arr[arr%2==0]
print(even)   # ellame one D array mari varum

[2 4 6]


In [14]:
even =arr[(arr%2==0) | (arr==1)]
print(even)

[1 2 4 6]


In [3]:
even = np.where(arr%2==0,arr,0)
print(even)

[[0 2 0]
 [4 0 6]]


In [1]:
import numpy as np

In [3]:
rng = np.random.default_rng()
print(rng.integers(1,31))

15


In [5]:
print(rng.integers(low=1,high=31))

13


In [7]:
print(rng.integers(low=1,high=31,size=(3,3)))

[[ 2 21 11]
 [ 4  6 28]
 [27  4  4]]


In [10]:
print(np.random.uniform(low=1,high=100,size=5))

[92.38194922  1.49644534 41.59356539 38.95333698 34.94270578]


In [11]:
arr = np.array(["hii","hello","bye"])

In [20]:
rng.shuffle(arr)


In [21]:
print(arr)

['hello' 'hii' 'bye']


In [24]:
print(rng.choice(arr))

bye


In [25]:
import os

In [26]:
print(os.getcwd())

C:\Users\Admin\OneDrive\Documents\CourseNotes\DA\python_files


In [27]:
arr = np.array([1,2,3,4,5,6])
np.save("task.npy",arr)

In [29]:
read=np.load("task.npy")
print(read)

[1 2 3 4 5 6]


In [38]:
arr1 = np.array([7,8,9])
np.save("task.npz",arr,arr1)

In [39]:
read=np.load("task.npz")
print(read)

FileNotFoundError: [Errno 2] No such file or directory: 'task.npz'