## Numpy


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
array = [1,2,3,4,5]

In [4]:
type(array)

list

In [7]:
array = array*2

In [100]:
array =[array]*2
array

[[[1, 2, 3, 4, 5, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]],
 [[1, 2, 3, 4, 5, 1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]]]

In [9]:
for i in array:
    i=i+2
    print(i)

3
4
5
6
7
3
4
5
6
7


In [10]:
arr = np.array([array])

In [12]:
type(arr)

numpy.ndarray

In [14]:
arr1=np.array([1]) # 0 D


arr2=np.array([1,2,3,4]) # 1D


arr3= np.array([
    [1,2,3],
    [4,5,6]
]) #2 D

arr4= np.array([     # 3 D
    [
        [1,2,3],
        [4,5,6]
    ],
    
     [
        [1,2,3],
        [4,5,6]
     ]

])

In [19]:
arr4.shape

(2, 2, 3)

In [28]:
print(arr4.size)

12


In [29]:
print(len(arr4))

2


In [30]:
type(arr1)

numpy.ndarray

In [32]:
print(arr1.dtype)

int64


int 8 -- bytes  --> 256 -->  -128 - 0 - 128
int 16
int 32
int 64


In [46]:
arr = np.array([1,2,3,4,130],dtype=np.int8)
arr = arr.astype(np.int8)

print(arr)
print(arr.dtype)

OverflowError: Python integer 130 out of bounds for int8

In [40]:
arr.dtype

dtype('int8')

In [48]:
arr.nbytes

5

In [50]:
arr= np.array(["hii","hello","welcomehdsunsdk"])
arr.dtype

dtype('<U15')

In [54]:
arr = np.array([1,2,3,4,130],dtype=np.bool_)
arr.dtype

dtype('bool')

In [111]:
arr3= np.array([
    [1,2,3],
    [4,5,6],
    [22,33,44]
]) 

print(arr3[1:3:1, 0:1:1])

[[ 4]
 [22]]


In [107]:
print(arr3[1,:2:,1])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [66]:
print(arr3[-1])

[4 5 6]


In [69]:
arr=np.array([20,43,6,5,3])
print(arr[1:4:2])

[43  5]


In [81]:
print(arr3[1:3:2])

[[4 5 6]]


In [82]:
print(arr[1])

43


In [85]:
print(arr3[2,2])

44


In [42]:
arr4= np.array([     # 3 D
    [
        [1,2,3],
        [4,5,6]
    ],
    
     [
        [1,2,3],
        [4,5,6]
     ]

])

In [87]:
print(arr4[0,1,2])

6


In [1]:
import numpy as np

In [11]:
data = np.zeros((3,6))

In [12]:
data

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
da=np.ones((4,4))

In [19]:
da

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
data=np.full((9,2),43)

In [25]:
data

array([[43, 43],
       [43, 43],
       [43, 43],
       [43, 43],
       [43, 43],
       [43, 43],
       [43, 43],
       [43, 43],
       [43, 43]])

In [28]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [60]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.random.rand(3,3)

array([[0.88928976, 0.19009563, 0.31432478],
       [0.68948036, 0.90805646, 0.15261344],
       [0.87399714, 0.29037197, 0.73374013]])

In [43]:
arr4.shape

(2, 2, 3)

In [46]:
arr4.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [47]:
arr4.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
arr4.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [58]:
arr4.reshape(2,1,6)

array([[[1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6]]])

In [61]:
s= arr4.flatten()
s

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [62]:
s

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [63]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [64]:
r=arr4.ravel()

In [65]:
r

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [66]:
r

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [67]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [68]:
arr4.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [69]:
arr4.ravel()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [70]:
np.ravel(arr4)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [71]:
arr4.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [72]:
a=np.array([1,2,3,4,5])

In [79]:
print(a+10)

[61 62 63 64 65]


In [80]:
a

array([51, 52, 53, 54, 55])

In [81]:
for i in a:
    a+=10
    print(i)

51
62
73
84
95


In [82]:
print(a*2)

[202 204 206 208 210]


In [83]:
a

array([101, 102, 103, 104, 105])

In [84]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [85]:
b=np.array([2,2,2])
b

array([2, 2, 2])

In [86]:
print(arr4*b)

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 2  4  6]
  [ 8 10 12]]]


In [90]:
a=np.array([[2],[2],[2],[2]])

In [91]:
a

array([[2],
       [2],
       [2],
       [2]])

In [92]:
print(a+b)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [99]:
print(b.sum(axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [109]:
arr =arr4.sum(axis=0)
arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [103]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [106]:
np.sqrt(arr4)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]])

In [110]:
np.sqrt(arr)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162]])

In [112]:
np.power(arr,3)

array([[   8,   64,  216],
       [ 512, 1000, 1728]])

In [113]:
np.exp(arr)

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05]])

In [114]:
np.log(arr)

array([[0.69314718, 1.38629436, 1.79175947],
       [2.07944154, 2.30258509, 2.48490665]])

In [115]:
np.abs(arr)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [116]:
np.round(arr)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [117]:
np.sum(arr)

np.int64(42)

In [118]:
np.min(arr)

np.int64(2)

In [119]:
np.max(arr)

np.int64(12)

In [120]:
np.mean(arr)

np.float64(7.0)

In [121]:
np.median(arr)

np.float64(7.0)

In [122]:
np.std(arr)

np.float64(3.415650255319866)

In [123]:
np.var(arr)

np.float64(11.666666666666666)

In [124]:
np.argmin(arr)

np.int64(0)

In [142]:
arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [126]:
np.argmax(arr)

np.int64(5)

In [127]:
age = np.array([23,43,55,22,11,65,34,44])

value= age>30
value

array([False,  True,  True, False, False,  True,  True,  True])

In [132]:
print(age[(age>=30) | (age<=40)] )

[23 43 55 22 11 65 34 44]


In [133]:
print(age[~(age>=30)] )

[23 22 11]


In [140]:
array = np.where(age>=30, "High","Low")

In [141]:
array

array(['Low', 'High', 'High', 'Low', 'Low', 'High', 'High', 'High'],
      dtype='<U4')

In [145]:
arr[arr>=5]

array([ 6,  8, 10, 12])

In [144]:
arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [154]:
array = np.where(arr>=5,arr,-1)

In [155]:
array

array([[-1, -1,  6],
       [ 8, 10, 12]])

In [162]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a,b))

32


In [163]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [164]:
import numpy as nd