## Numpy

In [1]:
import numpy as np

In [2]:
array=[1,2,3,4]

In [3]:
array

[1, 2, 3, 4]

In [4]:
type(array)

list

In [5]:
array=array+1

TypeError: can only concatenate list (not "int") to list

In [6]:
arr=np.array(array)

In [12]:
arr**3

array([ 1,  8, 27, 64])

In [13]:
type(arr)

numpy.ndarray

0D ==> 1
1D ==> [1,2,3,4,5]
2D ===> matrix 

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr

array([1, 2, 3, 4])

int8 ---> -128 -0-128
int16 
int32
int64


In [31]:
arr = np.array([1,2,3,4,130]).astype(np.int8)

In [32]:
arr.dtype

dtype('int8')

In [34]:
arr = np.array([1,2,3,4,130]).astype(np.int8)

In [40]:
arr = np.array([122,223,3,4]).astype(np.str_)

In [44]:
arr = np.array([122,223,3,4]).astype(np.bool_)

In [45]:
arr.dtype

dtype('bool')

In [55]:
arr=np.array([
    [1,2,3],
    [2,3,4],
    [3,3,4]
])
             

In [48]:
print(arr)

[[1 2 3]
 [2 3 4]]


In [49]:
arr.dtype

dtype('int64')

In [50]:
type(arr)

numpy.ndarray

In [52]:
arr.shape

(2, 3)

In [53]:
arr.size

6

In [56]:
print(len(arr))

3


In [57]:
arr[0]

array([1, 2, 3])

In [58]:
arr=np.array([
    [1,2,3],
    [2,3,4],
    [3,3,4]
])

In [59]:
arr[0]

array([1, 2, 3])

In [61]:
arr[2]

array([3, 3, 4])

In [67]:
arr[:3:1,1::1]

array([[2, 3],
       [3, 4],
       [3, 4]])

In [70]:
arr[::-1]

array([[3, 3, 4],
       [2, 3, 4],
       [1, 2, 3]])

In [1]:
import numpy as np

In [6]:
arr = np.zeros((5,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr=np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr=np.full((5,5),44)

In [18]:
print(arr)

[[44 44 44 44 44]
 [44 44 44 44 44]
 [44 44 44 44 44]
 [44 44 44 44 44]
 [44 44 44 44 44]]


In [25]:
arr=np.arange(2,100,10)
print(arr)

[ 2 12 22 32 42 52 62 72 82 92]


In [32]:
arr=np.linspace(0,500,6)
print(arr)

[  0. 100. 200. 300. 400. 500.]


In [34]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
arr=np.empty(3)
print(arr)

[ 1.23558247e-259  9.48973138e-312 -0.00000000e+000]


In [51]:
arr=np.random.randint(1,100,5)

In [52]:
print(arr)

[55 20 89 31 16]


In [70]:
arr=np.array([
    [1,2,3],
    [2,3,4]
])
print(arr)

[[1 2 3]
 [2 3 4]]


In [73]:
arr=arr.reshape(2,4)
print(arr)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [79]:
arr = np.array([
    [
        [1, 2, 3],
        [1, 2, 3]
    ],
    [
        [4, 5, 6],
        [4, 5, 6]
    ]
])
arr.shape

(2, 2, 3)

In [81]:
arr=arr.reshape(3,2,2)
print(arr)

[[[1 2]
  [3 1]]

 [[2 3]
  [4 5]]

 [[6 4]
  [5 6]]]


In [82]:
a=arr.flatten()
print(a)

[1 2 3 1 2 3 4 5 6 4 5 6]


In [84]:
b=arr.ravel()
print(b)

[1 2 3 1 2 3 4 5 6 4 5 6]


In [85]:
print(arr)

[[[1 2]
  [3 1]]

 [[2 3]
  [4 5]]

 [[6 4]
  [5 6]]]


In [86]:
print(b+arr)

ValueError: operands could not be broadcast together with shapes (12,) (3,2,2) 

In [99]:
a=np.array([1,2,3],[1,2,3],[1,2,3])
b=np.array([1],[1],[1])

print(a.shape())
print(b.shape)


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [100]:
print(a.shape)
print(b.shape)

(3,)
(1,)


In [101]:
print(a+b)

[2 3 4]


In [1]:
import numpy as np

In [9]:
arr =np.array([1,2,3,4])
# print(arr+10)

In [3]:
print(arr-1)

[0 1 2 3]


In [4]:
print(arr**2)

[ 1  4  9 16]


In [5]:
arr1=np.array([1])
print(arr+arr1)

[2 3 4 5]


In [10]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [11]:
arr = np.array([22,44,34,67,23])
arr

array([22, 44, 34, 67, 23])

In [23]:
sq = np.sqrt(arr)

In [22]:
pow = np.power(arr,9)
pow

array([    1207269217792,   618121839509504,    60716992766464,
       27206534396294947,     1801152661463])

In [17]:
np.exp(arr)

array([3.58491285e+09, 1.28516001e+19, 5.83461743e+14, 1.25236317e+29,
       9.74480345e+09])

In [31]:
np.floor(sq)

array([4., 6., 5., 8., 4.])

In [32]:
np.ceil(sq)

array([5., 7., 6., 9., 5.])

In [33]:
np.log(arr)

array([3.09104245, 3.78418963, 3.52636052, 4.20469262, 3.13549422])

In [37]:
print(np.sum(arr))

190


In [38]:
arr = np.array([
    [
        [1, 2, 3],
        [1, 2, 3]
    ],
    [
        [4, 5, 6],
        [4, 5, 6]
    ]
])

In [52]:
arr.sum(axis = 1)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [68]:
data=np.array([33,43,56,75])
d=data[data>=50]
d

array([56, 75])

In [56]:
d

array([False, False,  True, False])

In [72]:
print(data[~ (data>40) ])

[33]


In [74]:
d=np.`e(data>50 ,"above 50","below")
print(d)

['below' 'below' 'above 50' 'above 50']


In [84]:
a=np.array([[2,3,4,6],[2,3,4,5]])
b=np.array([[3,4,5,6],[5,6,78,5]])



In [85]:
print(a*b)

[[  6  12  20  36]
 [ 10  18 312  25]]
